#include <regex>
#include <string>
#include <string.h>
//Code generated by monic

bool m_match(std::string a, std::string regex)
{
	std::regex re(regex);
	return regex_match(a, re);
}
#include <iostream>
using namespace std;

string input;

int main(int argc, char **argv)
{
	if (argc >= 2)
	{
		if (true && (!strcmp(argv[1], "--test") || !strcmp(argv[1], "-t")))
		{
			if (argc >= 3)
			{
				if (true && m_match(argv[2], "[0-9]+"))
				{
					cout << "you input number" << endl;
				}
			}
			if (argc >= 3)
			{
				if (true && m_match(argv[2], ".*"))
				{
					cout << "not a number" << endl;
				}
			}
		}
	}
	return 0;
}